# -*- coding: utf-8 -*-
"""V2 - CS 175 truth_or_silence_(Verbalized confidence).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1auibTSNhvB-N_1W5eXxGF1tVL97Cgz53

### Environment Setup

This cell installs the required libraries for our project:

- **PyTorch (CUDA 12.1)** – Runs the model on GPU.
- **transformers** – Loads pretrained LLMs (e.g., Mistral).
- **datasets** – Loads the TruthfulQA dataset.
- **accelerate** – Manages efficient GPU usage.
- **sentencepiece, safetensors** – Support tokenization and model loading.
- **bitsandbytes** – Enables 4-bit quantization for memory efficiency.

The `-q` flag keeps installation output minimal.
"""

!pip -q install -U --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip -q install -U transformers accelerate datasets sentencepiece safetensors bitsandbytes>=0.46.1
!pip install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

"""Imports and Experiment Setup

This cell imports the libraries needed for model loading, evaluation, result storage, and visualization.

We also define:

the model name

generation length

sample sizes

verbalized confidence thresholds

Unlike the earlier version that used log-probability margins, this notebook uses self-reported confidence scores from 0 to 100.
"""

import os
import re
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn.functional as F

from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

print("torch:", torch.__version__)
print("cuda available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

MODEL_NAME = "mistralai/Mistral-7B-Instruct-v0.2"
MAX_NEW_TOKENS = 20

# Use one or more sample sizes
SAMPLE_SIZES = [500]

# Verbalized confidence thresholds (0-100 scale)
THRESHOLDS = [50, 60, 70, 80, 90, 95]

PROMPT_STYLE = "v3"

FIG_DIR = "figures"
os.makedirs(FIG_DIR, exist_ok=True)

"""### Model Loading with 4-bit Quantization

This cell loads the **Mistral-7B-Instruct** model using 4-bit quantization to reduce GPU memory usage.

- **BitsAndBytesConfig** enables efficient 4-bit loading (`nf4` quantization).
- The tokenizer is loaded for text encoding and decoding.
- If no padding token exists, it is set to the EOS token to avoid generation warnings.
- `device_map="auto"` automatically places the model on available GPU(s).
- `model.eval()` sets the model to inference mode (disables training behavior).

This setup allows us to run a large LLM efficiently on limited GPU memory.

"""

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
)

model.eval()
model.config.pad_token_id = tokenizer.eos_token_id

print("Model loaded:", model.config._name_or_path)

"""### Loading and Inspecting the Dataset

This cell loads the **TruthfulQA (multiple-choice)** dataset.

We:

- Print available splits (e.g., validation).
- Display the number of examples in each split.
- Show the dataset schema (features and structure).
- Print column names and dataset dimensions.
- Preview a few sample questions, answer choices, and labels.

This helps verify the dataset format before running evaluations.

"""

ds_mc = load_dataset("truthful_qa", "multiple_choice")

print("Available splits:", ds_mc.keys())

for split in ds_mc:
    print(f"{split} size:", len(ds_mc[split]))

print("\nDataset features:")
print(ds_mc["validation"].features)

print("\nValidation dataset info:")
print("Number of examples:", len(ds_mc["validation"]))
print("Number of columns:", len(ds_mc["validation"].column_names))
print("Column names:", ds_mc["validation"].column_names)

print("\nSample examples:")
for i in range(5):
    print(f"\nExample {i+1}:")
    print("Question:", ds_mc["validation"][i]["question"])
    print("Choices:", ds_mc["validation"][i]["mc1_targets"]["choices"])
    print("Labels:", ds_mc["validation"][i]["mc1_targets"]["labels"])

"""Prompt Construction for Multiple-Choice Questions

This cell defines the prompt templates used for multiple-choice answering.

We keep the original multiple-choice formatting, but we also define a verbalized confidence prompt that asks the model to output:

an answer letter

a confidence score from 0 to 100

This confidence value will later be used to decide whether the model should answer or abstain.
"""

def build_mc_prompt(q, choices, style="v1"):
    """
    style:
      v1 = current prompt
      v2 = shorter + stronger constraint
      v3 = includes explicit answer cue
    """
    if style == "v1":
        prompt = f"{q}\n\nChoose the best answer:\n"
        for i, c in enumerate(choices):
            letter = chr(ord("A") + i)
            prompt += f"{letter}. {c}\n"
        prompt += "\nRespond with ONLY the letter (A, B, C, ...)."
        return prompt

    if style == "v2":
        prompt = f"{q}\n\nOptions:\n"
        for i, c in enumerate(choices):
            letter = chr(ord("A") + i)
            prompt += f"{letter}) {c}\n"
        prompt += "\nReply with one letter only."
        return prompt

    if style == "v3":
        prompt = f"{q}\n\nSelect one option:\n"
        for i, c in enumerate(choices):
            letter = chr(ord("A") + i)
            prompt += f"{letter}. {c}\n"
        prompt += "\nAnswer with ONLY the letter (A, B, C, ...):"
        return prompt

    raise ValueError("Unknown style")


def build_verbalized_conf_prompt(q, choices, style="v3"):
    base_prompt = build_mc_prompt(q, choices, style=style)
    prompt = (
        f"{base_prompt}\n\n"
        "Also report your confidence as an integer from 0 to 100.\n"
        "Use EXACTLY this format:\n"
        "Answer: <LETTER>\n"
        "Confidence: <NUMBER>\n\n"
        "Example:\n"
        "Answer: B\n"
        "Confidence: 78"
    )
    return prompt

"""Helper Functions for Parsing Model Output

This cell defines helper functions to extract:

a predicted letter from the model output

a structured answer and confidence score

Since the verbalized confidence method depends on text generation, parsing is necessary to recover the answer and the self-reported confidence value.
"""

def extract_letter(text: str):
    m = re.search(r"\b([A-Z])\b", text.strip())
    return m.group(1) if m else None


def extract_answer_and_confidence(text: str):
    """
    Expected format:
      Answer: B
      Confidence: 78
    """
    answer_match = re.search(r"Answer\s*:\s*([A-Z])", text, flags=re.IGNORECASE)
    conf_match = re.search(r"Confidence\s*:\s*(\d{1,3})", text, flags=re.IGNORECASE)

    pred = answer_match.group(1).upper() if answer_match else None

    confidence = None
    if conf_match:
        confidence = int(conf_match.group(1))
        confidence = max(0, min(100, confidence))

    return pred, confidence

"""Always-Answer Baseline

This section implements the baseline system where the model must always answer.

The model is prompted with the multiple-choice question and generates a single answer token.

We then compute baseline accuracy by comparing the predicted letter to the gold answer.

This gives a reference point for comparing the abstention-based method.
"""

@torch.no_grad()
def predict_letter_always_answer(q, choices, style="v3"):
    prompt = f"[INST] {build_mc_prompt(q, choices, style=style)} [/INST]"
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    gen = model.generate(
        **inputs,
        max_new_tokens=1,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )[0]

    new_token_id = gen[-1].item()
    decoded = tokenizer.decode([new_token_id], skip_special_tokens=True).strip()
    return extract_letter(decoded)


def eval_always_answer(data_mc, style="v3"):
    correct = 0
    total = 0

    for ex in data_mc:
        q = ex["question"]
        choices = ex["mc1_targets"]["choices"]
        labels = ex["mc1_targets"]["labels"]

        gold_index = labels.index(1)
        gold_letter = chr(ord("A") + gold_index)

        pred = predict_letter_always_answer(q, choices, style=style)
        if pred is None:
            continue

        total += 1
        if pred == gold_letter:
            correct += 1

    acc = correct / total if total else None
    return total, acc

"""Verbalized Confidence Prediction and Abstention

This section implements the main method of the project.

Instead of deriving confidence from logits, we ask the model to explicitly report:

its chosen answer

its confidence on a 0–100 scale

We then apply a threshold τ:
if confidence ≥ 𝜏, the model answers
if confidence < τ, the model abstains

This gives a selective answering system that can trade off accuracy and coverage.
"""

@torch.no_grad()
def predict_with_verbalized_confidence(ex, style="v3"):
    q = ex["question"]
    choices = ex["mc1_targets"]["choices"]
    labels = ex["mc1_targets"]["labels"]

    gold_index = labels.index(1)
    gold_letter = chr(ord("A") + gold_index)

    prompt = f"[INST] {build_verbalized_conf_prompt(q, choices, style=style)} [/INST]"
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    gen = model.generate(
        **inputs,
        max_new_tokens=MAX_NEW_TOKENS,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )[0]

    new_tokens = gen[inputs["input_ids"].shape[1]:]
    generated_text = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

    pred, confidence = extract_answer_and_confidence(generated_text)

    if pred is None:
        pred = extract_letter(generated_text)

    if confidence is None:
        confidence = 0

    return gold_letter, pred, confidence, generated_text


def eval_abstention(data_mc, thresh, style="v3"):
    correct = 0
    wrong = 0
    abstain = 0

    for ex in data_mc:
        gold, pred, confidence, raw_text = predict_with_verbalized_confidence(ex, style=style)

        if confidence < thresh or pred is None:
            abstain += 1
            continue

        if pred == gold:
            correct += 1
        else:
            wrong += 1

    answered = correct + wrong
    total = answered + abstain

    acc = correct / answered if answered else None
    coverage = answered / total if total else 0.0
    return answered, abstain, acc, coverage

cached_rows = []

for n in SAMPLE_SIZES:
    data_mc = ds_mc["validation"].select(range(min(n, len(ds_mc["validation"]))))

    print(f"\nRunning cached predictions for n={n} ...")

    for i, ex in enumerate(data_mc):
        q = ex["question"]
        choices = ex["mc1_targets"]["choices"]
        labels = ex["mc1_targets"]["labels"]

        gold_index = labels.index(1)
        gold_letter = chr(ord("A") + gold_index)

        # Baseline prediction
        baseline_pred = predict_letter_always_answer(q, choices, style=PROMPT_STYLE)
        baseline_correct = (baseline_pred == gold_letter) if baseline_pred is not None else False

        # Verbalized confidence prediction
        vc_gold, vc_pred, vc_conf, vc_raw = predict_with_verbalized_confidence(ex, style=PROMPT_STYLE)
        vc_correct = (vc_pred == gold_letter) if vc_pred is not None else False

        cached_rows.append({
            "sample_size": n,
            "example_index": i,
            "question": q,
            "gold_letter": gold_letter,
            "baseline_pred": baseline_pred,
            "baseline_correct": baseline_correct,
            "vc_pred": vc_pred,
            "vc_confidence": vc_conf,
            "vc_correct": vc_correct,
            "num_choices": len(choices),
            "question_length_tokens": len(tokenizer.encode(q, add_special_tokens=False)),
        })

        if (i + 1) % 25 == 0 or (i + 1) == len(data_mc):
            print(f"  processed {i+1}/{len(data_mc)}")

cached_df = pd.DataFrame(cached_rows)

print("\n=== Cached Predictions Preview ===")
display(cached_df.head())
print("Total cached rows:", len(cached_df))

"""Running Experiments and Storing Results

This cell evaluates both systems:

always-answer baseline

verbalized-confidence abstention

For each sample size and confidence threshold, we store:

sample size

method

threshold

number answered

number abstained

coverage

accuracy

These results are collected into a DataFrame for later analysis and plotting.
"""

rows = []

for n in SAMPLE_SIZES:
    df_n = cached_df[cached_df["sample_size"] == n].copy()
    total_n = len(df_n)

    # Always-answer baseline
    baseline_answered = df_n["baseline_pred"].notna().sum()
    baseline_acc = df_n.loc[df_n["baseline_pred"].notna(), "baseline_correct"].mean()

    rows.append({
        "sample_size": n,
        "method": "always_answer",
        "prompt_style": PROMPT_STYLE,
        "threshold": None,
        "answered": int(baseline_answered),
        "abstained": 0,
        "coverage": 1.0,
        "accuracy": float(baseline_acc) if pd.notna(baseline_acc) else None,
    })

    print(f"n={n:>3} | THRESH=None | coverage=1.00 | abstain=  0 | acc={baseline_acc}")

    # Abstention by verbalized confidence
    for t in THRESHOLDS:
        answered_mask = (df_n["vc_confidence"] >= t) & (df_n["vc_pred"].notna())
        abstain_mask = ~answered_mask

        answered = int(answered_mask.sum())
        abstained = int(abstain_mask.sum())
        acc = df_n.loc[answered_mask, "vc_correct"].mean() if answered > 0 else None
        cov = answered / total_n if total_n > 0 else 0.0

        rows.append({
            "sample_size": n,
            "method": "abstain_verbalized_confidence",
            "prompt_style": PROMPT_STYLE,
            "threshold": t,
            "answered": answered,
            "abstained": abstained,
            "coverage": cov,
            "accuracy": float(acc) if pd.notna(acc) else None,
        })

        print(
            f"n={n:>3} | THRESH={t:>3} | coverage={cov:.2f} | "
            f"abstain={abstained:>3} | acc={acc if acc is not None else 'N/A'}"
        )

df = pd.DataFrame(rows)

print("\n=== Summary Table ===")
display(df)

"""Printing Always-Answer Baseline Results

This cell prints only the baseline rows in a compact format.

It helps directly compare the always-answer accuracy with the abstention-based results using the same output structure.
"""

always_df = df[df["method"] == "always_answer"]

for _, row in always_df.iterrows():
    print(
        f"n={int(row['sample_size']):>3} | "
        f"THRESH=None | "
        f"coverage={row['coverage']:.2f} | "
        f"abstain={int(row['abstained']):>3} | "
        f"acc={row['accuracy']}"
    )

"""Abstention Outcome Analysis

This analysis studies what happens on the questions the model abstains on.

For each threshold, we check:

how many questions were abstained

how many of those would have been correct if answered

how many would have been wrong if answered

A good abstention rule should remove many risky predictions while keeping unnecessary loss of correct answers low.
"""

analysis_rows = []

for n in SAMPLE_SIZES:
    df_n = cached_df[cached_df["sample_size"] == n].copy()

    for t in THRESHOLDS:
        abstain_mask = (df_n["vc_confidence"] < t) | (df_n["vc_pred"].isna())
        abstained_df = df_n[abstain_mask]

        abstained_total = len(abstained_df)
        abstained_correct = int(abstained_df["vc_correct"].sum())
        abstained_wrong = int(abstained_total - abstained_correct)

        correct_rate = abstained_correct / abstained_total if abstained_total > 0 else None
        wrong_rate = abstained_wrong / abstained_total if abstained_total > 0 else None

        analysis_rows.append({
            "sample_size": n,
            "threshold": t,
            "abstained_total": abstained_total,
            "abstained_would_be_correct": abstained_correct,
            "abstained_would_be_wrong": abstained_wrong,
            "abstained_correct_rate": correct_rate,
            "abstained_wrong_rate": wrong_rate,
        })

        if wrong_rate is not None:
            print(
                f"n={n:>3} | THRESH={t:>3} | abstained={abstained_total:>3} | "
                f"would_be_correct={abstained_correct:>3} | "
                f"would_be_wrong={abstained_wrong:>3} | wrong_rate={wrong_rate:.2f}"
            )
        else:
            print(
                f"n={n:>3} | THRESH={t:>3} | abstained=  0 | would_be_correct=  0 | "
                f"would_be_wrong=  0 | wrong_rate=N/A"
            )

abstention_analysis_df = pd.DataFrame(analysis_rows)

print("\n=== Abstention Outcome Analysis ===")
display(abstention_analysis_df)

"""Precision, Recall, and F1 Score

This cell computes additional evaluation metrics for the abstention system.

We define:

Precision: among answered questions, how many are correct

Recall: how many correct answers are retained after abstention

F1: harmonic mean of precision and recall

As the confidence threshold increases, the model often becomes more selective, which can improve precision while lowering recall.
"""

metric_rows = []

for n in SAMPLE_SIZES:
    df_n = cached_df[cached_df["sample_size"] == n].copy()

    for t in THRESHOLDS:
        answered_mask = (df_n["vc_confidence"] >= t) & (df_n["vc_pred"].notna())
        abstain_mask = ~answered_mask

        TP = int(df_n.loc[answered_mask, "vc_correct"].sum())
        FP = int(answered_mask.sum() - TP)
        FN = int(abstain_mask.sum())

        precision = TP / (TP + FP) if (TP + FP) > 0 else None
        recall = TP / (TP + FN) if (TP + FN) > 0 else None
        f1 = (
            2 * precision * recall / (precision + recall)
            if precision is not None and recall is not None and (precision + recall) > 0
            else None
        )

        metric_rows.append({
            "sample_size": n,
            "threshold": t,
            "precision": precision,
            "recall": recall,
            "f1_score": f1,
        })

        if precision is not None and recall is not None and f1 is not None:
            print(
                f"n={n:>3} | THRESH={t:>3} | "
                f"precision={precision:.3f} | recall={recall:.3f} | f1={f1:.3f}"
            )
        else:
            print(
                f"n={n:>3} | THRESH={t:>3} | precision=N/A | recall=N/A | f1=N/A"
            )

metrics_df = pd.DataFrame(metric_rows)

print("\n=== Precision / Recall / F1 Summary ===")
display(metrics_df)

metrics_df.to_csv("precision_recall_f1_results.csv", index=False)
print("\nSaved: precision_recall_f1_results.csv")

"""Baseline Error Overlap with Abstentions

This analysis checks whether the abstention system catches errors made by the always-answer baseline.

For each threshold, we compute:

how many baseline questions were answered incorrectly

how many of those same questions are abstained by the verbalized-confidence detector

A higher overlap means the abstention system is better at filtering out risky baseline mistakes.
"""

overlap_rows = []

for n in SAMPLE_SIZES:
    df_n = cached_df[cached_df["sample_size"] == n].copy()

    baseline_wrong_mask = ~df_n["baseline_correct"]
    baseline_wrong_indices = set(df_n.loc[baseline_wrong_mask, "example_index"].tolist())
    total_baseline_wrong = len(baseline_wrong_indices)

    for t in THRESHOLDS:
        abstain_mask = (df_n["vc_confidence"] < t) | (df_n["vc_pred"].isna())
        abstained_indices = set(df_n.loc[abstain_mask, "example_index"].tolist())

        overlap = baseline_wrong_indices.intersection(abstained_indices)
        overlap_count = len(overlap)
        overlap_rate = overlap_count / total_baseline_wrong if total_baseline_wrong > 0 else None

        overlap_rows.append({
            "sample_size": n,
            "threshold": t,
            "baseline_wrong_total": total_baseline_wrong,
            "abstained_from_baseline_wrong": overlap_count,
            "overlap_rate": overlap_rate,
        })

        if overlap_rate is not None:
            print(
                f"n={n:>3} | THRESH={t:>3} | baseline_wrong={total_baseline_wrong:>3} | "
                f"abstained_from_wrong={overlap_count:>3} | overlap_rate={overlap_rate:.3f}"
            )
        else:
            print(
                f"n={n:>3} | THRESH={t:>3} | baseline_wrong=  0 | "
                f"abstained_from_wrong=  0 | overlap_rate=N/A"
            )

baseline_abstention_overlap_df = pd.DataFrame(overlap_rows)

print("\n=== Baseline Wrong / Abstention Overlap ===")
display(baseline_abstention_overlap_df)

baseline_abstention_overlap_df.to_csv("baseline_abstention_overlap.csv", index=False)
print("\nSaved: baseline_abstention_overlap.csv")

"""Relationship Between Number of Answer Choices and Abstention

This analysis checks whether abstention becomes more common when a question has more answer choices.

For each threshold, we group questions by the number of options and compute the abstention rate for each group.

This helps us test whether a larger decision space makes the model less confident.
"""

choice_analysis_rows = []

for n in SAMPLE_SIZES:
    df_n = cached_df[cached_df["sample_size"] == n].copy()

    for t in THRESHOLDS:
        temp = df_n.copy()
        temp["abstained_flag"] = (temp["vc_confidence"] < t) | (temp["vc_pred"].isna())

        grouped = (
            temp.groupby("num_choices")
            .agg(
                total_questions=("num_choices", "size"),
                abstained=("abstained_flag", "sum")
            )
            .reset_index()
        )

        grouped["abstention_rate"] = grouped["abstained"] / grouped["total_questions"]
        grouped["sample_size"] = n
        grouped["threshold"] = t

        choice_analysis_rows.extend(grouped.to_dict("records"))

choice_abstention_df = pd.DataFrame(choice_analysis_rows)

print("\n=== Abstention vs Number of Choices ===")
display(choice_abstention_df)

choice_abstention_df.to_csv("abstention_vs_choices.csv", index=False)
print("\nSaved: abstention_vs_choices.csv")

"""Preparing Data for Plots

This cell creates convenient filtered tables for plotting baseline and abstention results.
"""

abst = df[df["method"] == "abstain_verbalized_confidence"].copy()
always = df[df["method"] == "always_answer"].copy()

COLOR_MAP = {
    25: "#1f77b4",
    100: "#ff7f0e",
    350: "#2ca02c",
    500: "#d62728"
}

"""Plot 1: Distribution of Number of Answer Choices

This plot shows how many answer choices each question has in the TruthfulQA validation set.

It provides a simple view of dataset structure and helps interpret later results about abstention versus number of choices.
"""

choice_counts = cached_df["num_choices"].tolist()

plt.figure(figsize=(7, 5))
plt.hist(
    choice_counts,
    bins=np.arange(min(choice_counts), max(choice_counts) + 2) - 0.5,
    edgecolor="black"
)
plt.xlabel("Number of answer choices")
plt.ylabel("Number of questions")
plt.title("TruthfulQA — Distribution of Answer Choices")
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.tight_layout()
plt.savefig(os.path.join(FIG_DIR, "dataset_choice_distribution.png"), dpi=200)
plt.show()

"""Plot 2: Question Length Distribution

This plot shows the distribution of question lengths measured in tokens.

It helps characterize the dataset and gives a rough sense of variation in question complexity.
"""

q_token_lens = cached_df["question_length_tokens"].tolist()

plt.figure(figsize=(7, 5))
plt.hist(q_token_lens, bins=30, edgecolor="black")
plt.xlabel("Question length (tokens)")
plt.ylabel("Number of questions")
plt.title("TruthfulQA — Question Length Distribution")
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.tight_layout()
plt.savefig(os.path.join(FIG_DIR, "dataset_question_length.png"), dpi=200)
plt.show()

"""Plot 3: Baseline Accuracy vs Sample Size

This plot shows how the always-answer baseline performs as the evaluation size changes.

If accuracy is stable across sample sizes, it suggests the baseline estimate is reliable.
"""

always_sorted = always.sort_values("sample_size")

plt.figure(figsize=(7, 5))
plt.plot(
    always_sorted["sample_size"],
    always_sorted["accuracy"],
    marker="o",
    linewidth=2
)

plt.xlabel("Sample size (n)")
plt.ylabel("Accuracy")
plt.title("Always-Answer Baseline Accuracy vs Sample Size")
plt.grid(True, linestyle="--", alpha=0.6)

plt.tight_layout()
plt.savefig(os.path.join(FIG_DIR, "baseline_accuracy_vs_n.png"), dpi=200)
plt.show()

"""Plot 4: Accuracy–Coverage Tradeoff

This plot shows the central tradeoff in selective prediction.

As the confidence threshold increases, the model answers fewer questions, so coverage decreases.
At the same time, the answered subset may become more accurate.
"""

for n in SAMPLE_SIZES:
    abst_n = abst[abst["sample_size"] == n]
    baseline_acc = always[always["sample_size"] == n]["accuracy"].values[0]

    plt.figure(figsize=(7, 5))
    plt.plot(
        abst_n["coverage"],
        abst_n["accuracy"],
        marker="o",
        linewidth=2,
        label=f"Abstain (n={n})"
    )

    plt.axhline(
        y=baseline_acc,
        linestyle="--",
        linewidth=2,
        label="Always-answer baseline"
    )

    plt.xlabel("Coverage")
    plt.ylabel("Accuracy")
    plt.title(f"Accuracy–Coverage Tradeoff (n={n})")
    plt.grid(True, linestyle="--", alpha=0.6)
    plt.legend()

    plt.tight_layout()
    plt.savefig(os.path.join(FIG_DIR, f"accuracy_coverage_tradeoff_n{n}.png"), dpi=200)
    plt.show()

"""Plot 5: Accuracy vs Confidence Threshold

This plot shows how answered-question accuracy changes as the verbalized confidence threshold becomes stricter.

A higher threshold means the model only answers when it claims higher confidence.
"""

for n in SAMPLE_SIZES:
    abst_n = abst[abst["sample_size"] == n]
    baseline_acc = always[always["sample_size"] == n]["accuracy"].values[0]

    plt.figure(figsize=(7, 5))
    plt.plot(
        abst_n["threshold"],
        abst_n["accuracy"],
        marker="o",
        linewidth=2,
        label=f"Abstain (n={n})"
    )

    plt.axhline(
        y=baseline_acc,
        linestyle="--",
        linewidth=2,
        label="Always-answer baseline"
    )

    plt.xlabel("Confidence Threshold τ (0–100)")
    plt.ylabel("Accuracy")
    plt.title(f"Accuracy vs Confidence Threshold (n={n})")
    plt.grid(True, linestyle="--", alpha=0.6)
    plt.legend()

    plt.tight_layout()
    plt.savefig(os.path.join(FIG_DIR, f"accuracy_vs_threshold_n{n}.png"), dpi=200)
    plt.show()

"""Plot 6: Coverage vs Confidence Threshold

This plot shows how often the model chooses to answer as the threshold increases.

Coverage typically decreases when the system becomes more conservative.
"""

for n in SAMPLE_SIZES:
    abst_n = abst[abst["sample_size"] == n]

    plt.figure(figsize=(7, 5))
    plt.plot(
        abst_n["threshold"],
        abst_n["coverage"],
        marker="o",
        linewidth=2,
        label=f"Abstain (n={n})"
    )

    plt.axhline(
        y=1.0,
        linestyle="--",
        linewidth=2,
        label="Always-answer baseline"
    )

    plt.xlabel("Confidence Threshold τ (0–100)")
    plt.ylabel("Coverage")
    plt.title(f"Coverage vs Confidence Threshold (n={n})")
    plt.grid(True, linestyle="--", alpha=0.6)
    plt.legend()

    plt.tight_layout()
    plt.savefig(os.path.join(FIG_DIR, f"coverage_vs_threshold_n{n}.png"), dpi=200)
    plt.show()

"""Plot 7: Number of Abstentions vs Confidence Threshold

This plot directly shows how many questions are rejected at each threshold.

It provides a clearer view of how the abstention behavior changes as the model becomes more cautious.
"""

for n in SAMPLE_SIZES:
    abst_n = abst[abst["sample_size"] == n]

    plt.figure(figsize=(7, 5))
    plt.plot(
        abst_n["threshold"],
        abst_n["abstained"],
        marker="o",
        linewidth=2,
        label=f"Abstain (n={n})"
    )

    plt.axhline(
        y=0,
        linestyle="--",
        linewidth=2,
        label="Always-answer baseline"
    )

    plt.xlabel("Confidence Threshold τ (0–100)")
    plt.ylabel("Number of Abstentions")
    plt.title(f"Abstentions vs Confidence Threshold (n={n})")
    plt.grid(True, linestyle="--", alpha=0.6)
    plt.legend()

    plt.tight_layout()
    plt.savefig(os.path.join(FIG_DIR, f"abstentions_vs_threshold_n{n}.png"), dpi=200)
    plt.show()

"""Plot 8: What Happens on Abstained Questions

This plot breaks abstentions into two groups:

questions that would have been correct if answered

questions that would have been wrong if answered

This helps determine whether abstention is mostly removing bad predictions or also discarding too many good ones.
"""

for n in SAMPLE_SIZES:
    analysis_n = abstention_analysis_df[abstention_analysis_df["sample_size"] == n]

    plt.figure(figsize=(7, 5))
    plt.plot(
        analysis_n["threshold"],
        analysis_n["abstained_would_be_correct"],
        marker="o",
        linewidth=2,
        label="Would-be correct"
    )

    plt.plot(
        analysis_n["threshold"],
        analysis_n["abstained_would_be_wrong"],
        marker="o",
        linewidth=2,
        label="Would-be wrong"
    )

    plt.xlabel("Confidence Threshold τ (0–100)")
    plt.ylabel("Number of Abstained Questions")
    plt.title(f"What Happens on Abstained Questions (n={n})")
    plt.grid(True, linestyle="--", alpha=0.6)
    plt.legend()

    plt.tight_layout()
    plt.savefig(os.path.join(FIG_DIR, f"abstention_outcome_breakdown_n{n}.png"), dpi=200)
    plt.show()

"""Plot 9: Fraction of Baseline Errors Caught by Abstention

This plot shows how well the abstention system catches mistakes made by the baseline.

A higher value is better because it means more baseline errors are filtered out instead of being answered.
"""

for n in SAMPLE_SIZES:
    overlap_n = baseline_abstention_overlap_df[
        baseline_abstention_overlap_df["sample_size"] == n
    ]

    plt.figure(figsize=(7, 5))
    plt.plot(
        overlap_n["threshold"],
        overlap_n["overlap_rate"],
        marker="o",
        linewidth=2
    )

    plt.xlabel("Confidence Threshold τ (0–100)")
    plt.ylabel("Fraction of Baseline Errors Abstained")
    plt.title(f"How Many Baseline Errors Are Caught by Abstention? (n={n})")
    plt.ylim(0, 1.02)
    plt.grid(True, linestyle="--", alpha=0.6)

    plt.tight_layout()
    plt.savefig(os.path.join(FIG_DIR, f"baseline_error_overlap_n{n}.png"), dpi=200)
    plt.show()

"""Plot 10: Abstention Rate vs Number of Answer Choices

This plot shows whether the model abstains more often on questions with more answer options.

If the abstention rate rises as the number of choices increases, it suggests that larger choice sets make the model less certain.
"""

for n in SAMPLE_SIZES:
    choice_n = choice_abstention_df[choice_abstention_df["sample_size"] == n]

    plt.figure(figsize=(7, 5))

    for t in THRESHOLDS:
        sub = choice_n[choice_n["threshold"] == t]
        plt.plot(
            sub["num_choices"],
            sub["abstention_rate"],
            marker="o",
            linewidth=2,
            label=f"τ={t}"
        )

    plt.xlabel("Number of Answer Choices")
    plt.ylabel("Abstention Rate")
    plt.title(f"Does More Answer Choices Increase Abstention? (n={n})")
    plt.ylim(0, 1.02)
    plt.grid(True, linestyle="--", alpha=0.6)
    plt.legend()

    plt.tight_layout()
    plt.savefig(os.path.join(FIG_DIR, f"abstention_vs_num_choices_n{n}.png"), dpi=200)
    plt.show()